# Generated by Django 2.2.6 on 2020-03-13 14:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profiles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('obb', django.db.models.manager.Manager()),
            ],
        ),
    ]
